SDAP 52 (Improved ranking algorithm speed)
apache/incubator-sdap-mudrod pull request #9
Opened 2018-03-23 03:36 UTC by Yongyao

2018-03-23 03:36 UTC, asfgit commented
Can one of the admins verify this patch?

2018-03-23 03:57 UTC, lewismc commented
@Yongyao can you please make sure to link the issue title to the JIRA issue title... from JIRA
```SDAP-52 Improve ranking speed```
It makes it easier for us to track the issues in our issue tracker.

2018-03-23 04:01 UTC, Yongyao commented
Changes made. @lewismc

2018-03-23 04:03 UTC, lewismc requested changes
Hi @Yongyao this is looking not bad. Please consider my comments. Additionally, do you ave any unit tests to verify the performance improvement? It would be preferred if we submit Unit tests for every patch from now on.

2018-03-23 04:03 UTC, lewismc commented on core/src/main/java/org/apache/sdap/mudrod/ssearch/Ranker.java
> +    public int compare(SResult o1, SResult o2) {
Please document ```SResult o1``` and ```SResult o2``` parameters.

2018-03-23 04:03 UTC, lewismc commented on core/src/main/java/org/apache/sdap/mudrod/ssearch/Ranker.java
> +      for (int i = 0; i < SResult.rlist.length; i++) {
Please use the enhanced for loop notation
```
for (SResult result: SResult.rlist.length)
```
This prevents the additional rlist([i]) accessors which is messy.

2018-03-23 04:03 UTC, lewismc commented on core/src/main/java/org/apache/sdap/mudrod/ssearch/Ranker.java
> +      if (prediction==1) { //different from weka where the return value is 1 or 2
The verified value should ALWAYS be on the left hand side. 
```if(1==prediction)```

2018-03-23 04:03 UTC, lewismc commented on core/src/main/java/org/apache/sdap/mudrod/ssearch/Ranker.java
> +        return 1;
Would you not just return the variable ```prediction```?

2018-04-04 16:29 UTC, lewismc approved these changes

2018-04-04 16:29 UTC, merged